language: node_js
node_js:
  - '4.1.2'
addons:
  sauce_connect: true
  code_climate:
    repo_token: ef1939588b1230f06a704858afb754c6434c41602b7997aee180b8afe30b34b3
install:
  - 'npm install -g npm'
  - 'npm install'
  - 'npm install -g bower grunt-cli node-gyp'
  - 'bower install'
script:
  - 'grunt test'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt e2e-sauce || false'
after_script:
  - codeclimate-test-reporter < test/reports/coverage/*/lcov.info
env:
  global:
    - secure: QHMeVROGTQEplE+OzMJJDdIfxcWh9ZZUbl0wElZS1GDLX4ysZzh7xhGQ/9yFGkCwJqNOeTwF1l/5shGPGlHet9F5fVN2eava7QTf/hAIfVZZUe2DXen5fyZ/RIJ/+v/8Ww9jht8Ml6ObZxhK84yOck2K4/Rx2AP5Dn9LSPbU1bx0/P9uvDH7TnBuebT3Ozjpi2ODq1yvUB49yp7q19zdXX8TXBbCHAxZlRC6IB1DCG8XGszAObvyHXnogmcvjWU3sDOXEPam30ZFbabmMsuqO/vXJLeig7knGda4IGm8PC0JK4hc4T3CrFelQO2l++NshZ6yew+lJq2+F/btZX9Dezn/KQB7IEynql4pZDsTvkdsXA/sy0B2auD8AhSb/RAded4q70I44yIk7ed+5z3U9YNDdPUW9VKvhu0VzIzsKTZtjcS5hh4Nr0Wa6x4/7BUeigROrpYE9nZs8i6vc4IztHmM6vKa7ksIvA3QFhR5DfMHjlVuzfXRGeTLfV79xcyJjoUjSzxG6r5wZ3y55AbKlhi30mxdXQB+UNWbX9NVapKe+V+XNz7GcNV1VgjeIEH1SQp2W4gQRItuYv8NhY08mM2OJI9XR+oRkg2U2LcNG9dluqs/zBEDOobEJUpmT+y47ERx1xHyElmcFGX0+V2gXTryby2Kr8qpzsgjeuX/C74=
    - secure: hrXEEJRLjvoEqZOIAipr8AB5uOA65iLjzRHpU6vet1WvDPW/12FXYHdLWzXI3EdJcHlPL+l6T8uQtZKdhqteOoCub4eD/2I82MEAiCXCL68Wv5IVpzIJ+IxzffZ9bYhs8SfhW9fQemod8NUd3gjK60zgav71iEiL1GMpjZtIes1RgUPB83EeaC2GV7/UzBoouyrY+eC/fnQChyXirxcKKptUXQsXe75c13SNDF2iiAKE+LPI5eFC+EeYxbofOxuypqPMXLZAkyEXWM40HVHT9phgG3Tr/y8SIRnZUG+sr55Bww243Nz3qgjLjw+XSrc45UXaTN5uQTDVVP/lI48Jn9Yc4SaMsabR5Hsgdvvx6rSycgkLo/lpDrD7aVgLvKC8CqF6KfL8ZWqUVAmKmV8Gs7NmumptdvOFGGKIdgLul5H2LD03X9yj/aStXPllDWb8ytZghS+kaPq1PL+/unYJe8iLmIYUt8lJyrwQ/ySCfClQfkNxDjKCTnJZA3TmcrUEbkUebPPt0sjjeFsIeXSkRn5oJ/KyeJGTaQeb+GLNvAArk6TbUn8Q2UteCf7IImEdw3zyKMGDqphvmRFNNQTLRUwVku1TZmp1d8u7B3Bq8fNsh4acy5O8Ys5gTnznrr+spOgHDRkuvyIvGNLT3LgTZ0BcWEuXP0gVn93ibLGUYfk=
sudo: false
